### ISSUE TITLE
What's your favorite CSS property?

### ISSUE THREAD

**Issue by michelbalzer** [anselmh/AMA#1]
First!!!!111111

**Comment by michelbalzer** [comment]
Well, you can name one for fun things, one for development time things, one for future potential and one for most mindblown.

**Comment by anselmh** [comment]
Here you go, quite a challenging question to be honest as there are so many cool props in CSS.

Fun things:
- I think it’s `animation-fill-mode` as it enables us to do amazing animations.

Development Time:
- `fill|stroke` is so great as you can inherit style from CSS to SVG (icons etc.) 

Future potential:
- `object-fit` when supported cross browser (polyfill is a pita due to performance of parsing CSS) as it contains lots of useful values that can be applied to achieve cool graphics effects, especially when bundled with for example `clip-path` property or similar cool stuff.

Most mindblown:
- `display` has blown my mind over the years with having `inline|block` first, then followed by the amazing `inline-block` value and now `flex` and `grid` which are two technologies of CSS that will be a huge deal in near future. When I started using CSS in 2004 I’d never imagined that development.
