### ISSUE TITLE
need some advice on starting out in web design

### ISSUE THREAD

**Issue by kbone89** [anselmh/AMA#19]
Hi Anselm,

I came across your articles on Smashing Magazine and delved further into your website and the WDRL Project.  You obviously have a ton of experience and knowledge about this world and I am hoping you could spare some time to answer a couple of my questions.

My goal is to be a UX/UI expert and do freelance consulting.  The internet has provided a wealth of information while simultaneously drowning me with insecurities of whether or not I am learning the right things or if what I am interested in can really lead me to a consulting career.  I keep researching more and more but feel as if I am drowning with the wealth of information available on the internet which is why I am reaching out to you with the questions below.

First, what moment or event caused you to think "I've made it in this world," or "I'm definitely on the right path"?

Second, is it realistic to think I can find a way forward with becoming an expert in HTML, CSS, and JS?  These seem to always be advertised as the "easy languages," but they are honestly what excite me the most!

Thanks so much for your time!!

**Comment by anselmh** [comment]
Hi @kbone89, thanks so much for your questions. I’m happy to try to answer them as good as I can 🙂

> My goal is to be a UX/UI expert and do freelance consulting. The internet has provided a wealth of information while simultaneously drowning me with insecurities of whether or not I am learning the right things or if what I am interested in can really lead me to a consulting career. I keep researching more and more but feel as if I am drowning with the wealth of information available on the internet which is why I am reaching out to you with the questions below.

Let me say this sounds great already. You seem to research already a lot and discover things on your own — a good path to follow.

> First, what moment or event caused you to think "I've made it in this world," or "I'm definitely on the right path"?

Heh, I think so far I never reached the moment “I’ve made it in this world” and I’m not sure I ever will. I think it’s important to realize that especially in our industry we will never stop learning. On the other hand, it’s also important to realize that this is how everyone in our industry works — always learning, exploring, testing out something new. So while I never had that thinking of “having made it” I also don’t feel the need for it, since I’m as good as other people in the industry — maybe some have special knowledge in some special field but apart from that we’re all just exploring :)
Regarding “being on the right path” that is something you should feel yourself when after some time, especially some trouble with clients etc, you still think you want to do this as your main job. I had no particular event for that though.

> Second, is it realistic to think I can find a way forward with becoming an expert in HTML, CSS, and JS?  These seem to always be advertised as the "easy languages," but they are honestly what excite me the most!

Fair question but it’s hard to give a good answer to it. The issue is, some people learn easier, faster than others. However, it’s relatively easy to start with basic HTML, CSS and this should be doable in a few weeks (to understand how it works, to a apply it for basic things). JavaScript on the other hand is much harder to learn if you’re not familiar to other programming languages, for example. On the other hand it’s also relatively easy to start by applying some easy jQuery scripts to your sample project.
I think the most important thing is to learn the basics of all these languages very well before you apply a tool like jQuery, React, Angular or similar. They change all the time but if you are confident writing plain JavaScript you will be able to apply any new tool with low effort later on.

Now to become an expert at these languages, I think it takes years of experience. I wouldn’t call myself a JavaScript expert for example. I definitely have good JS-knowledge but wouldn’t say at an expert level. For HTML and CSS I’d agree to an expert level but even there I can still learn a lot of new stuff every year. And it doesn’t help you much to know all JavaScript language-features, routines, etc. if you don’t apply it responsibly and build a solution that works for the very special ecosystem called the web browser.
While other programming languages are harder and more complex to learn, they are often relatively easy to apply since you have one target system that is predictable. However in the web, there are so many unpredictable, always changing target browsers, systems, networks, which makes it hard to build a good solution for it.
