### ISSUE TITLE
What do you feel is missing from CSS?

### ISSUE THREAD

**Issue by sindresorhus** [anselmh/AMA#5]
Anything it should officially adopt from Sass?

**Comment by anselmh** [comment]
In total honesty I don’t think we need much more functionality from Sass in CSS. Most things that belong to Sass and make sense in there wouldn’t make any sense in a live parsing environment.

I’d be great to have color functions (`lighten`, `darken`) in CSS though. And while I always wanted to have nesting in CSS as well, I believe this would cause much more trouble if used by all developers in plain CSS than in Sass. And we all know that even in the Sass environment this is becoming a bigger issue due to massively increased selector specificity and therefore file sizes.

We will get variables in CSS (though they work a bit differently which is also cool), we have partials but cannot solve the performance issues of `@import` in CSS, mixins/fn are IMO to complex for CSS itself. And we have `calc()` for calculations which is way cooler than static calcs in Sass.
