### ISSUE TITLE
What's the most difficult thing about being a web developer today?

### ISSUE THREAD

**Issue by sindresorhus** [anselmh/AMA#6]

**Comment by anselmh** [comment]
**Staying up to date these days.** With more tools, frameworks, libraries, buzzwords, design patterns coming out each day it gets very hard for a web developer to stay up to date and sane. Many people can’t figure out what’s the right way to do things nowadays and prioritize wrong things (tools over concepts). That is because the community creates a hype about every new framework etc.—and I think this harms regular developers (I mean devs who do normal projects like a normal website with CMS integration for some small to mid business).
We need to consolidate and merge tools, tooling workflows, technologies, design approaches and focus on the really important things in web development again: Proper concepts (technical, visual, content), accessibility, progressive enhancement. Tools should help us achieve that but stay absolutely in background so that no developer wastes hours of work by configuring some gulp task.

**Comment by hglattergotz** [comment]
> Many people can’t figure out what’s the right way to do things nowadays and prioritize wrong things (tools over concepts).

I am sure you spend considerable time reading because of the newsletter you curate, but how do you decide what to prioritize on?
Agreed, concepts are more important than tools, but you still have to at least know about them on the surface.
Can you give some tips for maintaining a healthy "personal filter"?
I go through phases with this which range from ignoring twitter, newsletters (yours too, sorry), etc. for days or even weeks to feeling paralyzed by the insane number of links that sound interesting and that clog up my to-do lists.

Thanks

**Comment by anselmh** [comment]
> I am sure you spend considerable time reading because of the newsletter you curate, but how do you decide what to prioritize on?

Yes, I do. I spend approximately (and in average) about 4-5hrs per week on curating the content. That is a rough estimate and doesn’t take reading twitter etc into account, just the time for reading and sorting out. Here’s how I curate content for the newsletter:
1. Open all links that might be interesting
2. Instantly read the summary / quick scan the article and if not interesting for WDRL, close tab
3. If interesting it’ll stay open
4. On Wednesday/Thursday I usually take 2-3 hours to read all remaining articles, then put them into WDRL if I still think they fit in there and have some importance. 
5. If I recognize there’s too much content for one week in the letter, I shift articles from one to another upcoming WDRL issue. If they’re shifted to next week, I re-consider them the next week.

This works out quite well so far but is of course taking a lot of time. Usually I do at least every 1-2 days a quick scan and quick sort-out session (1/2hr or so). Hope I understood your question correctly.

> Agreed, concepts are more important than tools, but you still have to at least know about them on the surface.

I fully agree on that. It’s not that you shouldn’t learn your tools. But it’s more important to prioritize the technical concept over tooling because it has more effect on the outcome.

> Can you give some tips for maintaining a healthy "personal filter"?

Yes. If you don’t have the time to play with cool technologies or frameworks that come out freshly, don’t touch them. In that case, don’t follow any immediate hype but just wait a little bit. I recognized that waiting a few weeks or months is a healthy filter to only dig deeper into things that might really be relevant. Frameworks, tools, libraries change so quickly today that you should be sure to choose them if you are sure they will live for at least 1-2 years.

If you have a tool that is solid, stable and works great for you – stick around with that one unless you think you should really exchange it for real reasons (not just because there’s a cooler way to do now).

It doesn’t help anyone if you’re stuck trying out a new framework that is claimed the next big thing if you first need to learn it, can’t match deadlines, have no colleagues who can maintain it as well and if your company or you need to exchange it again for another one next year because it’s not maintained or deprecated anymore. 

> I go through phases with this which range from ignoring twitter, newsletters (yours too, sorry), etc. for days or even weeks to feeling paralyzed by the insane number of links that sound interesting and that clog up my to-do lists.

No worries. I don’t expect my readers to read it every week and of course not to read every link. Just pick the links and articles that you find really interesting and take yourself the time to read them. In that case it is important to only have a few articles so that you really can match your goal to read it over the next days. Even I sometimes have articles open for more than a week which I really wanted to read and try out the examples but don’t have the time for it. Finally I often close the tabs as I realize I won’t have the time for it and it’s not mission critical to know the content of it. It’s human to not know everything.

**Comment by hglattergotz** [comment]
Thank you for taking the time to respond in such detail. Its funny, I use the "tab method" too and I have found that I rarely go back to the links I start to accumulate in tools built for that. I put them there in the first place because I am worried that I might be missing something.
