### ISSUE TITLE
Is it a lot of work to run an email newsletter?

### ISSUE THREAD

**Issue by sindresorhus** [anselmh/AMA#7]
https://wdrl.info

Are there some weeks you just feel like skipping it?
What motivates you to ship a new one every week?

**Comment by anselmh** [comment]
Great question. Indeed there are weeks and days when I don’t want to do anything for the WDRL. It works fine to skip curating content for 1-2 days per week although collecting links is a all-days job (yes I read my whole Twitter timeline and other resources as well).

There are weeks when I have much work-load or are ill. Then it’s hard to focus and I try to shift the writing part of WDRL to the next morning (I usually write better in the morning). Writing is the part of WDRL that needs focus and concentration and therefore the most fragile one.

But still, there is the motivation to send the letter because I receive great feedback from subscribers that they rely on my list to get up to date, that people love to read my texts. But most importantly, I want to help other people who have no time to curate all the content on their own with my list. So my motivation basically are my subscribers who are a very lovely bunch of people.
